Repository nunit/nunit, pull requests merged in 2018-10, with the labels that each got.

#3044 Lazy description creation in ComparisonConstraints
  src/NUnitFramework/framework/Constraints/ComparisonConstraint.cs
  src/NUnitFramework/framework/Constraints/GreaterThanConstraint.cs
  src/NUnitFramework/framework/Constraints/GreaterThanOrEqualConstraint.cs
  src/NUnitFramework/framework/Constraints/LessThanConstraint.cs
  src/NUnitFramework/framework/Constraints/LessThanOrEqualConstraint.cs
Labels: awaiting:review

#3051 Update BUILDING.md
  BUILDING.md
Labels: is:docs

#3040 Fix ContainsConstraint ignoring IgnoreCase for collection
  src/NUnitFramework/framework/Constraints/ContainsConstraint.cs
  src/NUnitFramework/tests/Constraints/ContainsConstraintTests.cs
Labels: awaiting:review

#3062 Timeout failures on MacOS #3014
  src/NUnitFramework/tests/Attributes/RepeatableTestsWithTimeoutAttributesTests.cs
Labels: awaiting:discussion, awaiting:review

#3081 Byte ranges no longer fail when they end on a boundary
  src/NUnitFramework/framework/Internal/ValueGenerator.ByteValueGenerator.cs
  src/NUnitFramework/tests/Attributes/RangeAttributeTests.cs
Labels: awaiting:review
