Repository nunit/nunit, pull requests merged in 2018-04, with the labels that each got.

#2776 Fixed deadlocks on known synchronization contexts
  src/NUnitFramework/framework/Internal/AsyncInvocationRegion.cs
  src/NUnitFramework/framework/Internal/AwaitAdapter.cs
  src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs
  src/NUnitFramework/framework/nunit.framework.csproj
  src/NUnitFramework/testdata/On.cs
  src/NUnitFramework/testdata/SynchronizationContextFixture.cs
  src/NUnitFramework/tests/Extensions.cs
  src/NUnitFramework/tests/SynchronizationContextTests.cs
  src/NUnitFramework/tests/nunit.framework.tests.csproj
Labels: awaiting:review

#2815 Readonly properties
  src/NUnitFramework/framework/Api/FrameworkController.cs
  src/NUnitFramework/framework/Attributes/TestCaseAttribute.cs
  src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs
  src/NUnitFramework/framework/Attributes/TestFixtureAttribute.cs
  src/NUnitFramework/framework/Attributes/TestFixtureSourceAttribute.cs
  src/NUnitFramework/framework/Attributes/ValueSourceAttribute.cs
  src/NUnitFramework/framework/Constraints/CollectionContainsConstraint.cs
  src/NUnitFramework/framework/Constraints/Constraint.cs
  src/NUnitFramework/framework/Constraints/ConstraintResult.cs
  src/NUnitFramework/framework/Constraints/DictionaryContainsKeyConstraint.cs
  src/NUnitFramework/framework/Constraints/DictionaryContainsValueConstraint.cs
  src/NUnitFramework/framework/Interfaces/AssertionResult.cs
  src/NUnitFramework/framework/Interfaces/ResultState.cs
  src/NUnitFramework/framework/Interfaces/TNode.cs
  src/NUnitFramework/framework/Interfaces/TestOutput.cs
  src/NUnitFramework/framework/Internal/Commands/TestCommand.cs
  src/NUnitFramework/framework/Internal/Execution/QueuingEventListener.cs
  src/NUnitFramework/framework/Internal/Execution/TestWorker.cs
  src/NUnitFramework/framework/Internal/Execution/WorkItem.cs
  src/NUnitFramework/framework/Internal/Execution/WorkItemQueue.cs
  src/NUnitFramework/framework/Internal/Filters/CompositeFilter.cs
  src/NUnitFramework/framework/Internal/Filters/NotFilter.cs
  src/NUnitFramework/framework/Internal/Filters/ValueMatchFilter.cs
  src/NUnitFramework/framework/Internal/GenericMethodHelper.cs
  src/NUnitFramework/framework/Internal/Results/TestResult.cs
  src/NUnitFramework/framework/Internal/RuntimeFramework.cs
  src/NUnitFramework/framework/Internal/TestExecutionContext.cs
  src/NUnitFramework/framework/Internal/TestParameters.cs
  src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs
  src/NUnitFramework/nunitlite.tests/CommandLineTests.cs
  src/NUnitFramework/nunitlite/ResultSummary.cs
  src/NUnitFramework/nunitlite/TextUI.cs
  src/NUnitFramework/nunitlite/Tokenizer.cs
  src/NUnitFramework/testdata/ActionAttributeFixture.cs
  src/NUnitFramework/tests/Constraints/CollectionOrderedConstraintTests.cs
  src/NUnitFramework/tests/Constraints/NUnitEqualityComparerTests.cs
  src/NUnitFramework/tests/Internal/EventListenerTextWriterTests.cs
  src/NUnitFramework/tests/Syntax/ArbitraryConstraintMatching.cs
Labels: is:refactor

#2819 Only run AppVeyor PR build against open PRs
  appveyor.yml
Labels: is:build

#2453 Null guard in BuildMessage
  src/NUnitFramework/framework/Guard.cs
  src/NUnitFramework/framework/Internal/ExceptionHelper.cs
  src/NUnitFramework/framework/Internal/Results/TestResult.cs
  src/NUnitFramework/tests/Internal/ExceptionHelperTests.cs
  src/NUnitFramework/tests/Internal/Results/TestResultApiTests.cs
Labels: awaiting:review

#2833 Use longer BusyExecIdle to avoid CI failures
  src/NUnitFramework/tests/Internal/TestWorkerTests.cs
Labels: awaiting:review

#2805 Removed boxing and eager range creation
  src/NUnitFramework/framework/Attributes/RangeAttribute.cs
  src/NUnitFramework/framework/Attributes/ValuesAttribute.cs
  src/NUnitFramework/framework/Internal/ParamAttributeTypeConversions.cs
  src/NUnitFramework/framework/Internal/Reflect.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.ByteValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.DecimalValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.DefaultValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.DoubleValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.Int16ValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.Int32ValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.Int64ValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.SByteValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.SingleValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.UInt16ValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.UInt32ValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.UInt64ValueGenerator.cs
  src/NUnitFramework/framework/Internal/ValueGenerator.cs
  src/NUnitFramework/testdata/RangeTestFixture.cs
  src/NUnitFramework/tests/Attributes/RangeAttributeTests.RangeWithExpectedConversions.cs
  src/NUnitFramework/tests/Attributes/RangeAttributeTests.cs
  src/NUnitFramework/tests/TestUtilities/StubParameterInfo.cs
Labels: awaiting:review, is:refactor
