Repository nunit/nunit, pull requests merged in 2019-07, with the labels that each got.

#3019 Attempt to fix hangs by using Sleep(1) instead of Sleep(0) for the polyfill's replacement of Thread.Yield
  src/NUnitFramework/framework/Compatibility/System.Threading/SpinWait.cs
Labels: awaiting:review

#3303 Check type of actual argument using consistent helper method
  src/NUnitFramework/framework/Constraints/EmptyDirectoryConstraint.cs
  src/NUnitFramework/framework/Constraints/ExceptionTypeConstraint.cs
  src/NUnitFramework/framework/Constraints/StringConstraint.cs
  src/NUnitFramework/tests/HelperConstraints.cs
Labels: awaiting:review, is:refactor

#3309 Simplify code in EventListenerTextWriter
  NUnit.sln.DotSettings
  src/NUnitFramework/framework/Internal/Execution/EventListenerTextWriter.cs
Labels: awaiting:review, is:refactor

#3308 Fix disposal in EnumerablesComparer
  src/NUnitFramework/framework/Constraints/Comparers/EnumerablesComparer.cs
Labels: awaiting:review

#3305 Remove unused methods
  src/NUnitFramework/framework/Attributes/RandomAttribute.cs
  src/NUnitFramework/framework/Compatibility/System.Collections.Concurrent/ConcurrentQueue.cs
  src/NUnitFramework/framework/Constraints/EqualConstraintResult.cs
  src/NUnitFramework/framework/Internal/Builders/ProviderCache.cs
  src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs
  src/NUnitFramework/framework/Internal/TestExecutionContext.cs
Labels: awaiting:review, is:refactor

#3310 Increase timeout for CI and use events rather than spin waits in tests
  src/NUnitFramework/framework/Compatibility/System.Threading/ManualResetEventSlim.cs
  src/NUnitFramework/tests/AwaitableReturnTypeTests.cs
Labels: awaiting:review

#3304 CheckString should not be a generic method
  src/NUnitFramework/framework/Constraints/FileOrDirectoryExistsConstraint.cs
Labels: awaiting:review, is:refactor

#3321 Keep dependencies up to date
  .editorconfig
  build.cake
  src/NUnitFramework/framework/nunit.framework.csproj
  src/NUnitFramework/nunitlite.tests/nunitlite.tests.csproj
  src/NUnitFramework/nunitlite/nunitlite.csproj
  src/NUnitFramework/tests/nunit.framework.tests.csproj
Labels: awaiting:review

#3322 Speed up build script by removing unnecessary builds
  src/NUnitFramework/mock-assembly/mock-assembly.csproj
  src/NUnitFramework/slow-tests/slow-nunit-tests.csproj
  src/NUnitFramework/testdata/nunit.testdata.csproj
  src/NUnitFramework/tests/app.config
Labels: closed:done, is:build

#3326 Update CHANGES.md
  CHANGES.md
Labels: awaiting:review, is:docs

#3318 Fix AwaitAdapter terminology
  NUnit.sln.DotSettings
  src/NUnitFramework/framework/Internal/AsyncToSyncAdapter.cs
  src/NUnitFramework/framework/Internal/AwaitAdapter.cs
  src/NUnitFramework/framework/Internal/DefaultBlockingAwaitAdapter.cs
  src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs
Labels: awaiting:review, is:refactor

#3317 Fix check for parameterless delegate
  src/NUnitFramework/framework/Internal/ExceptionHelper.cs
  src/NUnitFramework/tests/Internal/ExceptionHelperTests.cs
Labels: closed:done
