Repository nunit/nunit, pull requests merged in 2021-01, with the labels that each got.

#3646 IStructuralEquatable support
  src/NUnitFramework/framework/Constraints/Comparers/EquatablesComparer.cs
  src/NUnitFramework/framework/Constraints/Comparers/StructuralComparer.cs
  src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs
  src/NUnitFramework/framework/nunit.framework.csproj
  src/NUnitFramework/tests/Constraints/CollectionEqualsTests.cs
  src/NUnitFramework/tests/nunit.framework.tests.csproj
Labels: awaiting:review, hacktoberfest-accepted

#3701 Use reflection wrappers for Setup/Teardown methods (#3700)
  src/NUnitFramework/framework/Interfaces/IMethodInfo.cs
  src/NUnitFramework/framework/Interfaces/ITypeInfo.cs
  src/NUnitFramework/framework/Internal/Commands/SetUpTearDownItem.cs
  src/NUnitFramework/framework/Internal/Execution/SimpleWorkItem.cs
  src/NUnitFramework/framework/Internal/Execution/WorkItem.cs
  src/NUnitFramework/framework/Internal/MethodWrapper.cs
  src/NUnitFramework/framework/Internal/Reflect.cs
  src/NUnitFramework/framework/Internal/Tests/SetUpFixture.cs
  src/NUnitFramework/framework/Internal/Tests/Test.cs
  src/NUnitFramework/framework/Internal/Tests/TestFixture.cs
  src/NUnitFramework/framework/Internal/Tests/TestSuite.cs
  src/NUnitFramework/framework/Internal/TypeWrapper.cs
  src/NUnitFramework/tests/Attributes/RepeatAttributeTests.CustomMethodWrapper.cs
  src/NUnitFramework/tests/Attributes/RepeatAttributeTests.CustomTypeWrapper.cs
  src/NUnitFramework/tests/Internal/AsyncSetupTeardownTests.cs
Labels: awaiting:contributor, awaiting:review

#3711 Merge 3.13 release to master
  CHANGES.md
  LICENSE.txt
  build.cake
  nuget/framework/nunit.nuspec
  nuget/nunitlite/Program.cs
  nuget/nunitlite/Program.vb
  nuget/nunitlite/nunitlite.nuspec
  src/CommonAssemblyInfo.cs
  src/NUnitFramework/FrameworkVersion.cs
  src/NUnitFramework/nunitlite/TextUI.cs
Labels: awaiting:review

#3730 Date types difference output supported in equal constraint with tolerance
  src/NUnitFramework/framework/Constraints/DateTimes.cs
  src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs
  src/NUnitFramework/tests/Constraints/DateTimesTests.cs
  src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs
Labels: awaiting:review

#3728 chore: Remove references to Travis
  README.md
  appveyor.yml
  build.cake
Labels: awaiting:review

#3737 Fix non-numeric constraint with tolerance failure
  src/NUnitFramework/framework/Constraints/Numerics.cs
  src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs
  src/NUnitFramework/tests/Constraints/NumericsTest.cs
Labels: awaiting:review

#3741 Fix date on Ignored and Explicit Tests
  src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs
  src/NUnitFramework/framework/Internal/Execution/WorkItem.cs
  src/NUnitFramework/framework/Internal/TestExecutionContext.cs
  src/NUnitFramework/mock-assembly/MockAssembly.cs
  src/NUnitFramework/nunitlite.tests/NUnit2XmlOutputWriterTests.cs
  src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs
  src/NUnitFramework/nunitlite.tests/TextUIReportTests.cs
  src/NUnitFramework/nunitlite/OutputWriters/NUnit2XmlOutputWriter.cs
Labels: awaiting:review

#3744 Apply FixtureLifeCycle to parametrized tests
  src/NUnitFramework/framework/Internal/Commands/FixturePerTestCaseCommand.cs
  src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs
  src/NUnitFramework/framework/Internal/Execution/SimpleWorkItem.cs
  src/NUnitFramework/framework/Internal/Extensions/TestExtensions.cs
  src/NUnitFramework/testdata/AssemblyLevelLifeCycleFixture.cs
  src/NUnitFramework/testdata/LifeCycleFixture.cs
  src/NUnitFramework/tests/Attributes/LifeCycleAttributeTests.cs
Labels: awaiting:review
